# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nowMenu(object):
    def setupUi(self, nowMenu):
        nowMenu.setObjectName("nowMenu")
        nowMenu.resize(600, 400)
        nowMenu.setStyleSheet("background-color: rgb(36, 31, 49);")
        self.label = QtWidgets.QLabel(nowMenu)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(245, 194, 17);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.menuPushButton_1 = QtWidgets.QPushButton(nowMenu)
        self.menuPushButton_1.setGeometry(QtCore.QRect(225, 100, 150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPushButton_1.setFont(font)
        self.menuPushButton_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.menuPushButton_1.setObjectName("menuPushButton_1")
        self.menuPushButton_2 = QtWidgets.QPushButton(nowMenu)
        self.menuPushButton_2.setGeometry(QtCore.QRect(225, 150, 150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPushButton_2.setFont(font)
        self.menuPushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.menuPushButton_2.setObjectName("menuPushButton_2")
        self.menuPushButton_3 = QtWidgets.QPushButton(nowMenu)
        self.menuPushButton_3.setGeometry(QtCore.QRect(225, 200, 150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPushButton_3.setFont(font)
        self.menuPushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.menuPushButton_3.setObjectName("menuPushButton_3")
        self.menuPushButton_4 = QtWidgets.QPushButton(nowMenu)
        self.menuPushButton_4.setGeometry(QtCore.QRect(225, 250, 150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPushButton_4.setFont(font)
        self.menuPushButton_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.menuPushButton_4.setObjectName("menuPushButton_4")
        self.menuPushButton_5 = QtWidgets.QPushButton(nowMenu)
        self.menuPushButton_5.setGeometry(QtCore.QRect(225, 300, 150, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuPushButton_5.setFont(font)
        self.menuPushButton_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.menuPushButton_5.setObjectName("menuPushButton_5")

        self.retranslateUi(nowMenu)
        QtCore.QMetaObject.connectSlotsByName(nowMenu)

    def retranslateUi(self, nowMenu):
        _translate = QtCore.QCoreApplication.translate
        nowMenu.setWindowTitle(_translate("nowMenu", "Dialog"))
        self.label.setText(_translate("nowMenu", "Зараз"))
        self.menuPushButton_1.setText(_translate("nowMenu", "Курс Валют"))
        self.menuPushButton_2.setText(_translate("nowMenu", "Номера Валют"))
        self.menuPushButton_3.setText(_translate("nowMenu", "Графік Валют"))
        self.menuPushButton_4.setText(_translate("nowMenu", "Вивести в ексель"))
        self.menuPushButton_5.setText(_translate("nowMenu", "Вийти"))



