# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_window1(object):
    def setupUi(self, window1):
        window1.setObjectName("window1")
        window1.resize(600, 400)
        window1.setStyleSheet("background-color: rgb(36, 31, 49);")

        self.label = QtWidgets.QLabel(window1)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 50))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(245, 194, 17);\n"
"background-color: rgb(0, 0, 0);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.window1PushButton_1 = QtWidgets.QPushButton(window1)
        self.window1PushButton_1.setGeometry(QtCore.QRect(0, 0, 100, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.window1PushButton_1.setFont(font)
        self.window1PushButton_1.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.window1PushButton_1.setObjectName("window1PushButton_1")
        
        self.label2 = QtWidgets.QLabel(window1)
        self.label2.setGeometry(QtCore.QRect(0, 50, 600, 350))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label2.setFont(font)
        self.label2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(36, 31, 49);")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("label2")

        self.retranslateUi(window1)
        QtCore.QMetaObject.connectSlotsByName(window1)

    def retranslateUi(self, window1):
        _translate = QtCore.QCoreApplication.translate
        window1.setWindowTitle(_translate("window1", "Dialog"))
        self.label.setText(_translate("window1", "Курс Валют"))
        self.window1PushButton_1.setText(_translate("window1", "Меню"))
        self.label2.setText(_translate("window1", "Таблиця"))

